### PR TITLE
Subsampling

### PR DESCRIPTION
**Pull request by patrick-dd**
This is to add a subsampling method to the negative loss class.

I've used this in my work and thought it would be of use.

### CODE REVIEW

**Comment by kefirski** [comment]
Thank you very much for this contribution. 

There are some nuances in this implementation.

First of all, I think that there is no point to have additional parameter `classes` since this implementation imply having `classes = range(num_classes)` (e.g. we take representations of words by indexes of embedding matrix).


Also, could you replace 
```python
if self.classes:
```
with
```python 
if self.classes is not None:
```


And the most important, `numpy.random.choice` takes four positional parameters. In this implementation 
```python 
draw = choice(self.classes, n_samples, self.weights)
```
`self.weights` tractates as `replace` parameter and thus sampling performing from uniform distribution. To fix it, it is necessary to replace this line with 
```python 
draw = choice(self.classes, n_samples, p=self.weights)
```
but this will occur error since `∑ self.weights ≠ 1`. I think that the most straightforward way to fix it is to normalize `self.weights` and to add `assert` in `init` method in order to take away negative weights.

**Comment by patrick-dd** [comment]
Thanks for the comments! Good points all.

I'll drop `classes`, but change `self.classes is not None` to `self.weights is not None.` Rest incoprorated

**Comment by kefirski** [comment]
Thank you for operative fix!

But for now you have a little bug in
```python
draw = choice(range(self.num_classes, n_samples, p=self.weights))
```

Could you replace it with
```python
draw = choice(self.num_classes, n_samples, p=self.weights)
```
It will generate `n_samples` of numbers in `range(self.num_classes)` with condition in `self.weights`

Also I have noticed mysterious bracket [here](https://github.com/patrick-dd/pytorch_NEG_loss/blob/e37cf4174e29c7a198580f584dc1ab73e0d34cc8/NEG_loss/neg.py#L63)

**Comment by patrick-dd** [comment]
Good point, replaced!

**Pull request merged**
